---
title: 'Chapter 1 #3'
author: "Bonnie Romeo"
date: "2/4/2020"
output: word_document
---

```{r setup, include=FALSE}
library(ma391romeo)
```

A)

```{r}
p1 = function(x)0.65-0.01*x
p2 = function(x)0.65-0.01*x+0.00004*x^2
t = seq(0,20)

plot(t,p1(t),"l",lwd=3)

## Linear Approximation to quadratic function over [0,20] does not change by much, for values near 0 they are very close
```

B)

```{r}
# note the library package only includes fprime and bisection at this time #
c=0.00004
profit = function (x){((0.65-0.01*x+c*x^2)*(200+5*x)-0.45*x)}
dProfit = function(x){fprime(profit,x)}
t = seq(0,20)
```
```{r}
plot(t,profit(t),type="l",col="gray",lwd=3)
bisection(dProfit,0,20)
tab = data.frame(days=t,profit=profit(t))
print(tab)
```
C)
```{r}
## Sensitivity Analysis 
lo = seq(0.00001,0.00008,0.00001)
label=0
ans.days = 0
ans.profit=0
for (i in 1:length(lo)){
    c = lo[i]
    label[i]=sprintf("%.5f",c) #produce string from numbers
    profit = function (x){((0.65-0.01*x+c*x^2)*(200+5*x)-0.45*x)}
    dProfit = function(x){fprime(profit,x)}
    ans.days[i] = bisection(dProfit,0,20)
    ans.profit[i]=profit(ans.days[i])
}

result = data.frame(levelOff=lo,optimalDays = ans.days,profit=ans.profit)
print(result)
```


