---
title: 'Chapter 2 # 3'
author: "Bonnie Romeo"
date: "2/5/2020"
output: word_document
---

```{r setup, include=FALSE}
library(ma391romeo)
```

A)

```{r}
Blue = function(x){(0.05*x[1]*(1-x[1]/150000)-1/100000000*x[1]*x[2])}

Fin = function(x){(0.08*x[2]*(1-x[2]/400000)-1/100000000*x[1]*x[2])}


#MAX = Multiply by (-1)
Rev = function(x){(12*(0.05*x[1]*(1-x[1]/150000)-1/100000000*x[1]*x[2]) + 6*(0.08*x[2]*(1-x[2]/400000)-1/100000000*x[1]*x[2]))*(-1)}

x = c(50000,50000)

ans = optim(x,Rev, method = "L-BFGS-B") #Box conditions to increase the tol.
print(ans$par)
print(ans$value)
#Optimal Answers for # of Whales
Blue(ans$par)
Fin(ans$par)
```

B/C)
```{r}
#Sensitivity Analysis

R2 = function (r2){
  fr2 = function(x){
    (12*(0.05*x[1]*(1-x[1]/150000)-1/100000000*x[1]*x[2]) + 6*(r2*x[2]*(1-x[2]/400000)-1/100000000*x[1]*x[2]))*(-1)
  }
  x = c(50000, 50000)
  ans = optim(x,fr2, method = "L-BFGS-B")
  return(ans)
}

R2(0.08)

ans.x1 = 0 
ans.x2 = 0 
ans.rev = 0 

r = seq(0.04, 0.12, 0.01)
print(r) #Make sure the step is correct

#FOR Loop

for( i in 1:length(r)){
  ans = R2(r[i])
  ans.x1[i] = ans$par[1]
  ans.x2[i] = ans$par[2]
  ans.rev[i] = -1*(ans$value)
}
result = data.frame(growth_rate = r, x1 = ans.x1, x2 = ans.x2, revenue = ans.rev)
print(result)

#Not included: Changing the R2 Variable to the blue whale population function piece
```
D) Code does not work, graph on paper 


