---
title: '#5'
author: "Bonnie Romeo"
date: "1/26/2020"
output: word_document
---

```{r, include = FALSE}
#Helper Functions

fprime = function (f,a,h=0.0001){(f(a+h)-f(a-h))/(2*h)}


bisection = function(f,a,b,tol=0.0001){
  if (f(a)*f(b) > 0){
    return ("Boundary Conditions Not Met")
  }
  else{
    middle = a
    while (abs(f(middle))>tol){
      middle = (a+b)/2
      if (f(middle)*f(a)>0) (a = middle)
      else (b = middle)
      x=middle
      y=f(middle)
      ## if you want to "see" what happens at every step, take off the # of the next line ##
      #cat(sprintf("x-Val: %.4f ; f(x-val): %.4f\n",x,y))
    }
    return (middle)
  }
}


newton = function(f,x0, eps = 0.0001){
  xn = x0
  n = 1
  while(abs(f(xn))>eps & n < 1000){
    xn = xn-f(xn)/fprime(f,xn) 
    n = n + 123
  }
  return(xn)
}
```


```{r setup}
#A) NO TARIFFS

P = function(x){
  return(((339-0.01*x[1]-0.003*x[2])*x[1]
          +(399-0.004*x[1]-0.01*x[2])*x[2]
          -(400000+195*x[1]+225*x[2]))*-1)
}
x=c(500,500) #starting point for optimization
ans = optim(x,P,method="BFGS") #BFGS is a numerical technique used to incrementally calculate the Hessian for Newton
print(ans)

paste(c("Profits are maximized by selling:",round(ans$par[1])," 19 in TVs and ",
        round(ans$par[2])," 21 in TVs. Resulting in a profit of: $",
        format(round(-P(ans$par)),big.mark=",")),collapse="")
paste(c("Average Selling Price of 19 in set is: $",round(339-0.01*ans$par[1]-0.003*ans$par[2],2)),collapse="")
paste(c("Average Selling Price of 21 in set is: $",round(399-0.004*ans$par[1]-0.01*ans$par[2],2)),collapse="")


#NEW TARRIFFS

P = function(x){
  return(((339-0.01*x[1]-0.003*x[2])*x[1]
          +(399-0.004*x[1]-0.01*x[2])*x[2]
          -(400000+220*x[1]+250*x[2]))*-1)
}
x=c(500,500) #starting point for optimization
ans = optim(x,P,method="BFGS") #BFGS is a numerical technique used to incrementally calculate the Hessian for Newton
print(ans)

paste(c("Profits are maximized by selling:",round(ans$par[1])," 19 in TVs and ",
        round(ans$par[2])," 21 in TVs. Resulting in a profit of: $",
        format(round(-P(ans$par)),big.mark=",")),collapse="")

#How much does the tariff cost the company 
533641 - 282345

#Lost Sales 19 inch

4735 - 3809

#Lost Sales 21 inch

7043 - 6117

#Paid to gov?

(3809+6117)*25

#Lost Sales

251296-((3809+6117)*25)

#B) New Facilities

P = function(x){
  return((200000+(339-0.01*x[1]-0.003*x[2])*x[1]
          +(399-0.004*x[1]-0.01*x[2])*x[2]
          -(550000+(400000+195*x[1]+225*x[2])))*-1)
}

x=c(500,500) #starting point for optimization
ans = optim(x,P,method="BFGS") #BFGS is a numerical technique used to incrementally calculate the Hessian for Newton
print(ans)

paste(c("Profits are maximized by selling:",round(ans$par[1])," 19 in TVs and ",
        round(ans$par[2])," 21 in TVs. Resulting in a profit of: $",
        format(round(-P(ans$par)),big.mark=",")),collapse="")
paste(c("Average Selling Price of 19 in set is: $",round(339-0.01*ans$par[1]-0.003*ans$par[2],2)),collapse="")
paste(c("Average Selling Price of 21 in set is: $",round(399-0.004*ans$par[1]-0.01*ans$par[2],2)),collapse="")

#C) Min Tariff

R2 = function (r2){
  fr2 = function(x){
    return(((339-0.01*x[1]-0.003*x[2])*x[1]
            +(399-0.004*x[1]-0.01*x[2])*x[2]
            -(400000+(195+r2)*x[1]+(225+r2)*x[2]))*-1)
  }
  x = c(50000, 50000)
  ans = optim(x,fr2, method = "L-BFGS-B")
  return(ans)
}

ans.x1 = 0 
ans.x2 = 0 
ans.rev = 0 

r = seq(25, 35, 1.0)

#FOR Loop

for( i in 1:length(r)){
  ans = R2(r[i])
  ans.x1[i] = ans$par[1]
  ans.x2[i] = ans$par[2]
  ans.rev[i] = -1*(ans$value)
}
result = data.frame(Tariff = r, x1 = ans.x1, x2 = ans.x2, profit = ans.rev)
print(result)

#D)

plot(r, ans.rev)
plot(r, ans.x1)
plot(r, ans.x2)

lm(ans.rev~r)
lm(ans.x1~r)
lm(ans.x2~r)
```


